# Generated by Django 2.1 on 2018-08-15 22:08

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(help_text='Title that summarizes the year of work.', max_length=255, null=True, verbose_name='Title')),
                ('year', models.PositiveSmallIntegerField(help_text='Year of work', null=True, verbose_name='Year')),
                ('cover_image', cloudinary.models.CloudinaryField(blank=True, help_text='Cover image of work', max_length=255, null=True, verbose_name='Cover Image')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name_plural': 'Works',
                'verbose_name': 'Work',
            },
        ),
    ]
