# Generated by Django 2.1 on 2018-09-18 21:12

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyArtwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(help_text='Title that summarizes your year of artwork.', max_length=255, null=True, verbose_name='Title')),
                ('year', models.PositiveSmallIntegerField(help_text='The year your artwork is referenced too.', null=True, verbose_name='Year')),
                ('cover_image', cloudinary.models.CloudinaryField(help_text='Cover image that encompasses your year of artwork.', max_length=255, null=True, verbose_name='Cover Image')),
            ],
            options={
                'verbose_name': 'Yearly Artwork',
                'verbose_name_plural': 'Yearly Artworks',
            },
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
