# Generated by Django 2.1 on 2018-09-18 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20180918_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yearlyartwork',
            options={'verbose_name': 'Artwork Year', 'verbose_name_plural': 'Artwork Years'},
        ),
        migrations.AlterModelOptions(
            name='yearlyartworkdetail',
            options={'ordering': ['-yearly_artwork'], 'verbose_name': 'Artwork Detail', 'verbose_name_plural': 'Artwork Details'},
        ),
        migrations.AlterField(
            model_name='yearlyartworkdetail',
            name='yearly_artwork',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='years', to='content.YearlyArtwork', verbose_name='Artwork Year'),
        ),
    ]
