# Generated by Django 2.1 on 2018-09-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20180918_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkdetail',
            name='show_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Artwork Show'),
        ),
    ]
