# Generated by Django 2.1 on 2018-09-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_artworkdetail_show_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artworkdetail',
            options={'verbose_name': 'Artwork Detail', 'verbose_name_plural': 'Artwork Details'},
        ),
        migrations.AlterModelOptions(
            name='artworkyear',
            options={'ordering': ['-year'], 'verbose_name': 'Artwork Year', 'verbose_name_plural': 'Artwork Years'},
        ),
        migrations.AlterField(
            model_name='artworkyear',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Check means active / Uncheck means unactive', verbose_name='Active'),
        ),
    ]
