# Generated by Django 2.1 on 2018-09-19 13:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_auto_20180919_0433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculumvitaecatgories',
            options={'verbose_name': 'Curriculum Vitae', 'verbose_name_plural': 'Curriculum Vitae Information'},
        ),
        migrations.AddField(
            model_name='artworkdetail',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Artwork Video'),
        ),
        migrations.AlterField(
            model_name='artworkdetail',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Artwork Image'),
        ),
    ]
