# Generated by Django 2.1 on 2018-09-19 15:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20180919_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkdetail',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Maximum image size is 10 MB', max_length=255, null=True, verbose_name='Artwork Image'),
        ),
        migrations.AlterField(
            model_name='artworkdetail',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Maximum video size is 100 MB and accepted video types are mp4, webm, ogg, avi', max_length=255, null=True, verbose_name='Artwork Video'),
        ),
        migrations.AlterField(
            model_name='artworkyear',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(help_text='Cover image that encompasses your year of artwork. The maximum image size is 10 MB', max_length=255, null=True, verbose_name='Cover Image'),
        ),
    ]
