# Generated by Django 2.1 on 2018-09-26 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_collection_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artworkyear',
            options={'ordering': ['-year'], 'verbose_name': 'Artwork', 'verbose_name_plural': 'Artworks'},
        ),
        migrations.AlterModelOptions(
            name='curriculumvitaecatgories',
            options={'verbose_name': 'Curriculum Vitae', 'verbose_name_plural': 'Curriculum Vitae'},
        ),
    ]
