# Generated by Django 2.1 on 2018-09-26 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_generalinformation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalinformation',
            old_name='description',
            new_name='about_description',
        ),
        migrations.RenameField(
            model_name='generalinformation',
            old_name='email',
            new_name='public_email',
        ),
    ]
