# Generated by Django 2.1 on 2018-09-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_auto_20180926_1548'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneralInformation',
        ),
    ]
