# Generated by Django 2.1 on 2018-09-26 16:02

import django.contrib.sites.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_set_site_domain_and_name'),
        ('content', '0018_delete_generalinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInformation',
            fields=[
                ('site_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sites.Site')),
                ('public_email', models.EmailField(blank=True, help_text='Public facing contact email.', max_length=200, null=True, verbose_name='Email')),
                ('about_description', models.TextField(blank=True, help_text='Max length 1000 characters', max_length=1000, null=True, verbose_name='About Description')),
            ],
            bases=('sites.site',),
            managers=[
                ('objects', django.contrib.sites.models.SiteManager()),
            ],
        ),
    ]
