# Generated by Django 2.1 on 2018-09-26 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_generalinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalinformation',
            name='site_ptr',
        ),
        migrations.DeleteModel(
            name='GeneralInformation',
        ),
    ]
