# Generated by Django 2.1 on 2018-09-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_auto_20180926_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_email', models.EmailField(blank=True, help_text='Public facing contact email.', max_length=200, null=True, verbose_name='Email')),
                ('about_description', models.TextField(blank=True, help_text='Max length 1000 characters', max_length=1000, null=True, verbose_name='About Description')),
            ],
            options={
                'verbose_name': 'General Information',
                'verbose_name_plural': 'General Information',
            },
        ),
    ]
