# Generated by Django 2.1 on 2018-09-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_generalinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinformation',
            name='google_analytics',
            field=models.TextField(blank=True, help_text='Paste your google analytics code here', max_length=1000, null=True, verbose_name='Google Analytics Code'),
        ),
    ]
