# Generated by Django 2.1 on 2018-11-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_auto_20181029_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkyear',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='about_description',
            field=models.TextField(blank=True, help_text='Max length 1000 characters', max_length=5000, null=True, verbose_name='About Description'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='google_analytics',
            field=models.CharField(blank=True, help_text='Paste your google analytics code here, ex: UA-XXXXXXXXX-X', max_length=255, null=True, verbose_name='Google Analytics Code'),
        ),
    ]
