# Generated by Django 2.1 on 2018-11-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_auto_20181119_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinformation',
            name='about_description',
            field=models.TextField(blank=True, help_text='Max length 1000 characters', null=True, verbose_name='About Description'),
        ),
    ]
