# Generated by Django 2.1 on 2018-11-21 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_auto_20181121_0247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artworkdetail',
            options={'ordering': ['-id'], 'verbose_name': 'Artwork Detail', 'verbose_name_plural': 'Artwork Details'},
        ),
    ]
