# Generated by Django 2.1 on 2018-11-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_auto_20181121_0617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artworkdetail',
            options={'ordering': ['id'], 'verbose_name': 'Artwork Detail', 'verbose_name_plural': 'Artwork Details'},
        ),
        migrations.AlterField(
            model_name='curriculumvitaecatgories',
            name='category',
            field=models.CharField(choices=[('Solo Exhibitions', 'Solo Exhibitions'), ('Selected Group Exhibitions', 'Two Person and Selected Group Exhibitions'), ('Press/Publications', 'Press/Publications'), ('Artist Books/Catalogs', 'Artist Books/Catalogs')], max_length=255, null=True, verbose_name='CV Category'),
        ),
    ]
