# Generated by Django 2.1 on 2018-11-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_auto_20181122_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumvitaecatgories',
            name='category',
            field=models.CharField(choices=[('Solo Exhibitions', 'Solo Exhibitions'), ('Two Person and Selected Group Exhibitions', 'Two Person and Selected Group Exhibitions'), ('Press/Publications', 'Press/Publications'), ('Artist Books/Catalogs', 'Artist Books/Catalogs')], max_length=255, null=True, verbose_name='CV Category'),
        ),
    ]
