# Generated by Django 2.1 on 2018-11-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_auto_20181122_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculumvitaecatgories',
            name='category',
            field=models.CharField(choices=[(1, 'Solo Exhibitions'), (2, 'Two Person and Selected Group Exhibitions'), (3, 'Artist Books/Catalogs'), (4, 'Press/Publications')], max_length=255, null=True, verbose_name='CV Category'),
        ),
    ]
