# Generated by Django 2.1 on 2018-11-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_auto_20181122_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinformation',
            name='about_description',
            field=models.TextField(blank=True, null=True, verbose_name='About Description'),
        ),
    ]
