# Generated by Django 2.1 on 2018-11-22 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_auto_20181122_0611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculumvitaecatgories',
            options={'ordering': ['category'], 'verbose_name': 'Curriculum Vitae', 'verbose_name_plural': 'Curriculum Vitae'},
        ),
    ]
