# Generated by Django 2.1 on 2018-11-23 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0034_auto_20181122_0615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculumvitaedetail',
            options={'ordering': ['-year'], 'verbose_name': 'CV Detail', 'verbose_name_plural': 'CV Details'},
        ),
    ]
