# Generated by Django 2.1 on 2018-11-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_auto_20181123_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumvitaedetail',
            name='url',
            field=models.URLField(blank=True, help_text="Optional URL for article link'", max_length=255, null=True, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='instagram_handle',
            field=models.CharField(blank=True, help_text="Please omit @ symbol, just input the the handle e.g. 'fakehandle'", max_length=255, null=True, verbose_name='Instagram Handle'),
        ),
        migrations.AddField(
            model_name='generalinformation',
            name='instagram_url',
            field=models.URLField(blank=True, help_text="Please enter full url with https:// or http://'", max_length=255, null=True, verbose_name='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='generalinformation',
            name='google_analytics',
            field=models.CharField(blank=True, help_text='Paste your google analytics code here, e.g. UA-XXXXXXXXX-X', max_length=255, null=True, verbose_name='Google Analytics Code'),
        ),
    ]
