# Generated by Django 2.1 on 2019-02-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0037_auto_20181123_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinformation',
            name='menu_description',
            field=models.TextField(blank=True, null=True, verbose_name='Menu Description'),
        ),
    ]
